package com.dsh.m.dao;

import com.dsh.m.model.Goods;
import com.dsh.m.model.GoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int countByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int deleteByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int deleteByPrimaryKey(Integer goodsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	List<Goods> selectByExample(GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	Goods selectByPrimaryKey(Integer goodsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Goods record,
			@Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int updateByExample(@Param("record") Goods record,
			@Param("example") GoodsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Thu Nov 19 16:18:11 CST 2015
	 */
	int updateByPrimaryKey(Goods record);
}