package com.dsh.m.dao;

import com.dsh.m.model.GoodsPrice;
import com.dsh.m.model.GoodsPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int countByExample(GoodsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int deleteByExample(GoodsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int insert(GoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int insertSelective(GoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    List<GoodsPrice> selectByExample(GoodsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    GoodsPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") GoodsPrice record, @Param("example") GoodsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int updateByExample(@Param("record") GoodsPrice record, @Param("example") GoodsPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price
     *
     * @mbggenerated Thu Aug 06 15:53:39 CST 2015
     */
    int updateByPrimaryKey(GoodsPrice record);
}