package com.dsh.m.dao;

import com.dsh.m.model.PayAppoint;
import com.dsh.m.model.PaySmscode;
import com.dsh.m.model.PaySmscodeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PaySmscodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int countByExample(PaySmscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int deleteByExample(PaySmscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int insert(PaySmscode payAppiontInsert);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int insertSelective(PaySmscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    List<PaySmscode> selectByExample(PaySmscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    PaySmscode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") PaySmscode record, @Param("example") PaySmscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int updateByExample(@Param("record") PaySmscode record, @Param("example") PaySmscodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int updateByPrimaryKeySelective(PaySmscode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_smscode
     *
     * @mbggenerated Thu Nov 12 19:37:15 CST 2015
     */
    int updateByPrimaryKey(PaySmscode record);
}