package com.dsh.m.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dsh.m.model.PurchaseorderChild;
import com.dsh.m.model.PurchaseorderChildExample;

public interface PurchaseorderChildMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int countByExample(PurchaseorderChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int deleteByExample(PurchaseorderChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int insert(PurchaseorderChild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int insertSelective(PurchaseorderChild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	List<PurchaseorderChild> selectByExample(PurchaseorderChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	PurchaseorderChild selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int updateByExampleSelective(@Param("record") PurchaseorderChild record,
			@Param("example") PurchaseorderChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int updateByExample(@Param("record") PurchaseorderChild record,
			@Param("example") PurchaseorderChildExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int updateByPrimaryKeySelective(PurchaseorderChild record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchaseorder_child
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	int updateByPrimaryKey(PurchaseorderChild record);
	
	BigDecimal getRealAmountByOrderId(Integer orderid);
}