package com.dsh.m.dao;

import com.dsh.m.model.Settleaccount;
import com.dsh.m.model.SettleaccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettleaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int countByExample(SettleaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int deleteByExample(SettleaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int insert(Settleaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int insertSelective(Settleaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    List<Settleaccount> selectByExample(SettleaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    Settleaccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") Settleaccount record, @Param("example") SettleaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int updateByExample(@Param("record") Settleaccount record, @Param("example") SettleaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int updateByPrimaryKeySelective(Settleaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table settleaccount
     *
     * @mbggenerated Mon Jun 29 17:15:59 CST 2015
     */
    int updateByPrimaryKey(Settleaccount record);
}