package com.dsh.m.dao;

import com.dsh.m.model.SysSms;
import com.dsh.m.model.SysSmsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysSmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int countByExample(SysSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int deleteByExample(SysSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int insert(SysSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int insertSelective(SysSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    List<SysSms> selectByExample(SysSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    SysSms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysSms record, @Param("example") SysSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int updateByExample(@Param("record") SysSms record, @Param("example") SysSmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int updateByPrimaryKeySelective(SysSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_sms
     *
     * @mbggenerated Tue Nov 03 13:33:26 CST 2015
     */
    int updateByPrimaryKey(SysSms record);
}