package com.dsh.m.model;

import java.util.Date;

public class CustomerGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.id
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.customerid
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.goodsid
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.unit
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.sequence
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.count
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.money
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.lastdate
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Date lastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.createuser
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.createtime
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.updateuser
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.updatetime
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.zyx1
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Long zyx1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.zyx2
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Long zyx2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.zyx3
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private Integer zyx3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.zyx4
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private String zyx4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.zyx5
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private String zyx5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.ts
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private String ts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_goods.dr
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    private String dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.id
     *
     * @return the value of customer_goods.id
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.id
     *
     * @param id the value for customer_goods.id
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.customerid
     *
     * @return the value of customer_goods.customerid
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.customerid
     *
     * @param customerid the value for customer_goods.customerid
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.goodsid
     *
     * @return the value of customer_goods.goodsid
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.goodsid
     *
     * @param goodsid the value for customer_goods.goodsid
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.unit
     *
     * @return the value of customer_goods.unit
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.unit
     *
     * @param unit the value for customer_goods.unit
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.sequence
     *
     * @return the value of customer_goods.sequence
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.sequence
     *
     * @param sequence the value for customer_goods.sequence
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.count
     *
     * @return the value of customer_goods.count
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.count
     *
     * @param count the value for customer_goods.count
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.money
     *
     * @return the value of customer_goods.money
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.money
     *
     * @param money the value for customer_goods.money
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.lastdate
     *
     * @return the value of customer_goods.lastdate
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.lastdate
     *
     * @param lastdate the value for customer_goods.lastdate
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.createuser
     *
     * @return the value of customer_goods.createuser
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.createuser
     *
     * @param createuser the value for customer_goods.createuser
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.createtime
     *
     * @return the value of customer_goods.createtime
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.createtime
     *
     * @param createtime the value for customer_goods.createtime
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.updateuser
     *
     * @return the value of customer_goods.updateuser
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.updateuser
     *
     * @param updateuser the value for customer_goods.updateuser
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setUpdateuser(Integer updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.updatetime
     *
     * @return the value of customer_goods.updatetime
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.updatetime
     *
     * @param updatetime the value for customer_goods.updatetime
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.zyx1
     *
     * @return the value of customer_goods.zyx1
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Long getZyx1() {
        return zyx1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.zyx1
     *
     * @param zyx1 the value for customer_goods.zyx1
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setZyx1(Long zyx1) {
        this.zyx1 = zyx1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.zyx2
     *
     * @return the value of customer_goods.zyx2
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Long getZyx2() {
        return zyx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.zyx2
     *
     * @param zyx2 the value for customer_goods.zyx2
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setZyx2(Long zyx2) {
        this.zyx2 = zyx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.zyx3
     *
     * @return the value of customer_goods.zyx3
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public Integer getZyx3() {
        return zyx3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.zyx3
     *
     * @param zyx3 the value for customer_goods.zyx3
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setZyx3(Integer zyx3) {
        this.zyx3 = zyx3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.zyx4
     *
     * @return the value of customer_goods.zyx4
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public String getZyx4() {
        return zyx4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.zyx4
     *
     * @param zyx4 the value for customer_goods.zyx4
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setZyx4(String zyx4) {
        this.zyx4 = zyx4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.zyx5
     *
     * @return the value of customer_goods.zyx5
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public String getZyx5() {
        return zyx5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.zyx5
     *
     * @param zyx5 the value for customer_goods.zyx5
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setZyx5(String zyx5) {
        this.zyx5 = zyx5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.ts
     *
     * @return the value of customer_goods.ts
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.ts
     *
     * @param ts the value for customer_goods.ts
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setTs(String ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_goods.dr
     *
     * @return the value of customer_goods.dr
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_goods.dr
     *
     * @param dr the value for customer_goods.dr
     *
     * @mbggenerated Tue Jun 30 16:07:35 CST 2015
     */
    public void setDr(String dr) {
        this.dr = dr;
    }
}