package com.dsh.m.model;

public class GoodsSclass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sclass.sclassid
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    private Integer sclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sclass.sclassname
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    private String sclassname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sclass.bclassid
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    private Integer bclassid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sclass.sclassid
     *
     * @return the value of goods_sclass.sclassid
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    public Integer getSclassid() {
        return sclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sclass.sclassid
     *
     * @param sclassid the value for goods_sclass.sclassid
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    public void setSclassid(Integer sclassid) {
        this.sclassid = sclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sclass.sclassname
     *
     * @return the value of goods_sclass.sclassname
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    public String getSclassname() {
        return sclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sclass.sclassname
     *
     * @param sclassname the value for goods_sclass.sclassname
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    public void setSclassname(String sclassname) {
        this.sclassname = sclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sclass.bclassid
     *
     * @return the value of goods_sclass.bclassid
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    public Integer getBclassid() {
        return bclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sclass.bclassid
     *
     * @param bclassid the value for goods_sclass.bclassid
     *
     * @mbggenerated Wed Jun 17 15:46:43 CST 2015
     */
    public void setBclassid(Integer bclassid) {
        this.bclassid = bclassid;
    }
}