package com.dsh.m.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class GoodsCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public GoodsCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andTypeNumIsNull() {
            addCriterion("type_num is null");
            return (Criteria) this;
        }

        public Criteria andTypeNumIsNotNull() {
            addCriterion("type_num is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNumEqualTo(String value) {
            addCriterion("type_num =", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumNotEqualTo(String value) {
            addCriterion("type_num <>", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumGreaterThan(String value) {
            addCriterion("type_num >", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumGreaterThanOrEqualTo(String value) {
            addCriterion("type_num >=", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumLessThan(String value) {
            addCriterion("type_num <", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumLessThanOrEqualTo(String value) {
            addCriterion("type_num <=", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumLike(String value) {
            addCriterion("type_num like", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumNotLike(String value) {
            addCriterion("type_num not like", value, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumIn(List<String> values) {
            addCriterion("type_num in", values, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumNotIn(List<String> values) {
            addCriterion("type_num not in", values, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumBetween(String value1, String value2) {
            addCriterion("type_num between", value1, value2, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNumNotBetween(String value1, String value2) {
            addCriterion("type_num not between", value1, value2, "typeNum");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypePicIsNull() {
            addCriterion("type_pic is null");
            return (Criteria) this;
        }

        public Criteria andTypePicIsNotNull() {
            addCriterion("type_pic is not null");
            return (Criteria) this;
        }

        public Criteria andTypePicEqualTo(String value) {
            addCriterion("type_pic =", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicNotEqualTo(String value) {
            addCriterion("type_pic <>", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicGreaterThan(String value) {
            addCriterion("type_pic >", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicGreaterThanOrEqualTo(String value) {
            addCriterion("type_pic >=", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicLessThan(String value) {
            addCriterion("type_pic <", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicLessThanOrEqualTo(String value) {
            addCriterion("type_pic <=", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicLike(String value) {
            addCriterion("type_pic like", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicNotLike(String value) {
            addCriterion("type_pic not like", value, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicIn(List<String> values) {
            addCriterion("type_pic in", values, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicNotIn(List<String> values) {
            addCriterion("type_pic not in", values, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicBetween(String value1, String value2) {
            addCriterion("type_pic between", value1, value2, "typePic");
            return (Criteria) this;
        }

        public Criteria andTypePicNotBetween(String value1, String value2) {
            addCriterion("type_pic not between", value1, value2, "typePic");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNull() {
            addCriterion("is_show is null");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNotNull() {
            addCriterion("is_show is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowEqualTo(Boolean value) {
            addCriterion("is_show =", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotEqualTo(Boolean value) {
            addCriterion("is_show <>", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThan(Boolean value) {
            addCriterion("is_show >", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_show >=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThan(Boolean value) {
            addCriterion("is_show <", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThanOrEqualTo(Boolean value) {
            addCriterion("is_show <=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowIn(List<Boolean> values) {
            addCriterion("is_show in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotIn(List<Boolean> values) {
            addCriterion("is_show not in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowBetween(Boolean value1, Boolean value2) {
            addCriterion("is_show between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_show not between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsIndexIsNull() {
            addCriterion("is_index is null");
            return (Criteria) this;
        }

        public Criteria andIsIndexIsNotNull() {
            addCriterion("is_index is not null");
            return (Criteria) this;
        }

        public Criteria andIsIndexEqualTo(Short value) {
            addCriterion("is_index =", value, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexNotEqualTo(Short value) {
            addCriterion("is_index <>", value, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexGreaterThan(Short value) {
            addCriterion("is_index >", value, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexGreaterThanOrEqualTo(Short value) {
            addCriterion("is_index >=", value, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexLessThan(Short value) {
            addCriterion("is_index <", value, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexLessThanOrEqualTo(Short value) {
            addCriterion("is_index <=", value, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexIn(List<Short> values) {
            addCriterion("is_index in", values, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexNotIn(List<Short> values) {
            addCriterion("is_index not in", values, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexBetween(Short value1, Short value2) {
            addCriterion("is_index between", value1, value2, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsIndexNotBetween(Short value1, Short value2) {
            addCriterion("is_index not between", value1, value2, "isIndex");
            return (Criteria) this;
        }

        public Criteria andIsSaleIsNull() {
            addCriterion("is_sale is null");
            return (Criteria) this;
        }

        public Criteria andIsSaleIsNotNull() {
            addCriterion("is_sale is not null");
            return (Criteria) this;
        }

        public Criteria andIsSaleEqualTo(Boolean value) {
            addCriterion("is_sale =", value, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleNotEqualTo(Boolean value) {
            addCriterion("is_sale <>", value, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleGreaterThan(Boolean value) {
            addCriterion("is_sale >", value, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_sale >=", value, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleLessThan(Boolean value) {
            addCriterion("is_sale <", value, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleLessThanOrEqualTo(Boolean value) {
            addCriterion("is_sale <=", value, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleIn(List<Boolean> values) {
            addCriterion("is_sale in", values, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleNotIn(List<Boolean> values) {
            addCriterion("is_sale not in", values, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sale between", value1, value2, "isSale");
            return (Criteria) this;
        }

        public Criteria andIsSaleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sale not between", value1, value2, "isSale");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("ts is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("ts is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(String value) {
            addCriterion("ts =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(String value) {
            addCriterion("ts <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(String value) {
            addCriterion("ts >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(String value) {
            addCriterion("ts >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(String value) {
            addCriterion("ts <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(String value) {
            addCriterion("ts <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLike(String value) {
            addCriterion("ts like", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotLike(String value) {
            addCriterion("ts not like", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<String> values) {
            addCriterion("ts in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<String> values) {
            addCriterion("ts not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(String value1, String value2) {
            addCriterion("ts between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(String value1, String value2) {
            addCriterion("ts not between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andSortnoIsNull() {
            addCriterion("sortno is null");
            return (Criteria) this;
        }

        public Criteria andSortnoIsNotNull() {
            addCriterion("sortno is not null");
            return (Criteria) this;
        }

        public Criteria andSortnoEqualTo(Short value) {
            addCriterion("sortno =", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoNotEqualTo(Short value) {
            addCriterion("sortno <>", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoGreaterThan(Short value) {
            addCriterion("sortno >", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoGreaterThanOrEqualTo(Short value) {
            addCriterion("sortno >=", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoLessThan(Short value) {
            addCriterion("sortno <", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoLessThanOrEqualTo(Short value) {
            addCriterion("sortno <=", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoIn(List<Short> values) {
            addCriterion("sortno in", values, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoNotIn(List<Short> values) {
            addCriterion("sortno not in", values, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoBetween(Short value1, Short value2) {
            addCriterion("sortno between", value1, value2, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoNotBetween(Short value1, Short value2) {
            addCriterion("sortno not between", value1, value2, "sortno");
            return (Criteria) this;
        }

        public Criteria andDrIsNull() {
            addCriterion("dr is null");
            return (Criteria) this;
        }

        public Criteria andDrIsNotNull() {
            addCriterion("dr is not null");
            return (Criteria) this;
        }

        public Criteria andDrEqualTo(String value) {
            addCriterion("dr =", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotEqualTo(String value) {
            addCriterion("dr <>", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThan(String value) {
            addCriterion("dr >", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThanOrEqualTo(String value) {
            addCriterion("dr >=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThan(String value) {
            addCriterion("dr <", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThanOrEqualTo(String value) {
            addCriterion("dr <=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLike(String value) {
            addCriterion("dr like", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotLike(String value) {
            addCriterion("dr not like", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrIn(List<String> values) {
            addCriterion("dr in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotIn(List<String> values) {
            addCriterion("dr not in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrBetween(String value1, String value2) {
            addCriterion("dr between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotBetween(String value1, String value2) {
            addCriterion("dr not between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andZyx1IsNull() {
            addCriterion("zyx1 is null");
            return (Criteria) this;
        }

        public Criteria andZyx1IsNotNull() {
            addCriterion("zyx1 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx1EqualTo(Integer value) {
            addCriterion("zyx1 =", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1NotEqualTo(Integer value) {
            addCriterion("zyx1 <>", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1GreaterThan(Integer value) {
            addCriterion("zyx1 >", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1GreaterThanOrEqualTo(Integer value) {
            addCriterion("zyx1 >=", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1LessThan(Integer value) {
            addCriterion("zyx1 <", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1LessThanOrEqualTo(Integer value) {
            addCriterion("zyx1 <=", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1In(List<Integer> values) {
            addCriterion("zyx1 in", values, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1NotIn(List<Integer> values) {
            addCriterion("zyx1 not in", values, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1Between(Integer value1, Integer value2) {
            addCriterion("zyx1 between", value1, value2, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1NotBetween(Integer value1, Integer value2) {
            addCriterion("zyx1 not between", value1, value2, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx2IsNull() {
            addCriterion("zyx2 is null");
            return (Criteria) this;
        }

        public Criteria andZyx2IsNotNull() {
            addCriterion("zyx2 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx2EqualTo(String value) {
            addCriterion("zyx2 =", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotEqualTo(String value) {
            addCriterion("zyx2 <>", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2GreaterThan(String value) {
            addCriterion("zyx2 >", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2GreaterThanOrEqualTo(String value) {
            addCriterion("zyx2 >=", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2LessThan(String value) {
            addCriterion("zyx2 <", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2LessThanOrEqualTo(String value) {
            addCriterion("zyx2 <=", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2Like(String value) {
            addCriterion("zyx2 like", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotLike(String value) {
            addCriterion("zyx2 not like", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2In(List<String> values) {
            addCriterion("zyx2 in", values, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotIn(List<String> values) {
            addCriterion("zyx2 not in", values, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2Between(String value1, String value2) {
            addCriterion("zyx2 between", value1, value2, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotBetween(String value1, String value2) {
            addCriterion("zyx2 not between", value1, value2, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx3IsNull() {
            addCriterion("zyx3 is null");
            return (Criteria) this;
        }

        public Criteria andZyx3IsNotNull() {
            addCriterion("zyx3 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx3EqualTo(String value) {
            addCriterion("zyx3 =", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotEqualTo(String value) {
            addCriterion("zyx3 <>", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3GreaterThan(String value) {
            addCriterion("zyx3 >", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3GreaterThanOrEqualTo(String value) {
            addCriterion("zyx3 >=", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3LessThan(String value) {
            addCriterion("zyx3 <", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3LessThanOrEqualTo(String value) {
            addCriterion("zyx3 <=", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3Like(String value) {
            addCriterion("zyx3 like", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotLike(String value) {
            addCriterion("zyx3 not like", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3In(List<String> values) {
            addCriterion("zyx3 in", values, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotIn(List<String> values) {
            addCriterion("zyx3 not in", values, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3Between(String value1, String value2) {
            addCriterion("zyx3 between", value1, value2, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotBetween(String value1, String value2) {
            addCriterion("zyx3 not between", value1, value2, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx4IsNull() {
            addCriterion("zyx4 is null");
            return (Criteria) this;
        }

        public Criteria andZyx4IsNotNull() {
            addCriterion("zyx4 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx4EqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 =", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4NotEqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 <>", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4GreaterThan(Date value) {
            addCriterionForJDBCDate("zyx4 >", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 >=", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4LessThan(Date value) {
            addCriterionForJDBCDate("zyx4 <", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 <=", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4In(List<Date> values) {
            addCriterionForJDBCDate("zyx4 in", values, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4NotIn(List<Date> values) {
            addCriterionForJDBCDate("zyx4 not in", values, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4Between(Date value1, Date value2) {
            addCriterionForJDBCDate("zyx4 between", value1, value2, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zyx4 not between", value1, value2, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx5IsNull() {
            addCriterion("zyx5 is null");
            return (Criteria) this;
        }

        public Criteria andZyx5IsNotNull() {
            addCriterion("zyx5 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx5EqualTo(BigDecimal value) {
            addCriterion("zyx5 =", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5NotEqualTo(BigDecimal value) {
            addCriterion("zyx5 <>", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5GreaterThan(BigDecimal value) {
            addCriterion("zyx5 >", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("zyx5 >=", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5LessThan(BigDecimal value) {
            addCriterion("zyx5 <", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("zyx5 <=", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5In(List<BigDecimal> values) {
            addCriterion("zyx5 in", values, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5NotIn(List<BigDecimal> values) {
            addCriterion("zyx5 not in", values, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("zyx5 between", value1, value2, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zyx5 not between", value1, value2, "zyx5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_category
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 14 15:00:49 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_category
     *
     * @mbggenerated Mon Dec 14 15:00:49 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}