package com.dsh.m.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PayResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public PayResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_Id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_Id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_Id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_Id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_Id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_Id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_Id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_Id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_Id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_Id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_Id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_Id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_Id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_Id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameIsNull() {
            addCriterion("interface_Name is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameIsNotNull() {
            addCriterion("interface_Name is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameEqualTo(String value) {
            addCriterion("interface_Name =", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameNotEqualTo(String value) {
            addCriterion("interface_Name <>", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameGreaterThan(String value) {
            addCriterion("interface_Name >", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameGreaterThanOrEqualTo(String value) {
            addCriterion("interface_Name >=", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameLessThan(String value) {
            addCriterion("interface_Name <", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameLessThanOrEqualTo(String value) {
            addCriterion("interface_Name <=", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameLike(String value) {
            addCriterion("interface_Name like", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameNotLike(String value) {
            addCriterion("interface_Name not like", value, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameIn(List<String> values) {
            addCriterion("interface_Name in", values, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameNotIn(List<String> values) {
            addCriterion("interface_Name not in", values, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameBetween(String value1, String value2) {
            addCriterion("interface_Name between", value1, value2, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andInterfaceNameNotBetween(String value1, String value2) {
            addCriterion("interface_Name not between", value1, value2, "interfaceName");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNull() {
            addCriterion("request_Id is null");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNotNull() {
            addCriterion("request_Id is not null");
            return (Criteria) this;
        }

        public Criteria andRequestIdEqualTo(String value) {
            addCriterion("request_Id =", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotEqualTo(String value) {
            addCriterion("request_Id <>", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThan(String value) {
            addCriterion("request_Id >", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
            addCriterion("request_Id >=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThan(String value) {
            addCriterion("request_Id <", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThanOrEqualTo(String value) {
            addCriterion("request_Id <=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLike(String value) {
            addCriterion("request_Id like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotLike(String value) {
            addCriterion("request_Id not like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdIn(List<String> values) {
            addCriterion("request_Id in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotIn(List<String> values) {
            addCriterion("request_Id not in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdBetween(String value1, String value2) {
            addCriterion("request_Id between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotBetween(String value1, String value2) {
            addCriterion("request_Id not between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIsNull() {
            addCriterion("payment_id is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIsNotNull() {
            addCriterion("payment_id is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentIdEqualTo(Integer value) {
            addCriterion("payment_id =", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotEqualTo(Integer value) {
            addCriterion("payment_id <>", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdGreaterThan(Integer value) {
            addCriterion("payment_id >", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("payment_id >=", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLessThan(Integer value) {
            addCriterion("payment_id <", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdLessThanOrEqualTo(Integer value) {
            addCriterion("payment_id <=", value, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdIn(List<Integer> values) {
            addCriterion("payment_id in", values, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotIn(List<Integer> values) {
            addCriterion("payment_id not in", values, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdBetween(Integer value1, Integer value2) {
            addCriterion("payment_id between", value1, value2, "paymentId");
            return (Criteria) this;
        }

        public Criteria andPaymentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("payment_id not between", value1, value2, "paymentId");
            return (Criteria) this;
        }

        public Criteria andOrderAmtIsNull() {
            addCriterion("order_amt is null");
            return (Criteria) this;
        }

        public Criteria andOrderAmtIsNotNull() {
            addCriterion("order_amt is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAmtEqualTo(String value) {
            addCriterion("order_amt =", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotEqualTo(String value) {
            addCriterion("order_amt <>", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtGreaterThan(String value) {
            addCriterion("order_amt >", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtGreaterThanOrEqualTo(String value) {
            addCriterion("order_amt >=", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtLessThan(String value) {
            addCriterion("order_amt <", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtLessThanOrEqualTo(String value) {
            addCriterion("order_amt <=", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtLike(String value) {
            addCriterion("order_amt like", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotLike(String value) {
            addCriterion("order_amt not like", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtIn(List<String> values) {
            addCriterion("order_amt in", values, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotIn(List<String> values) {
            addCriterion("order_amt not in", values, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtBetween(String value1, String value2) {
            addCriterion("order_amt between", value1, value2, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotBetween(String value1, String value2) {
            addCriterion("order_amt not between", value1, value2, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("fee is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("fee is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(String value) {
            addCriterion("fee =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(String value) {
            addCriterion("fee <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(String value) {
            addCriterion("fee >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(String value) {
            addCriterion("fee >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(String value) {
            addCriterion("fee <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(String value) {
            addCriterion("fee <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLike(String value) {
            addCriterion("fee like", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotLike(String value) {
            addCriterion("fee not like", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<String> values) {
            addCriterion("fee in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<String> values) {
            addCriterion("fee not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(String value1, String value2) {
            addCriterion("fee between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(String value1, String value2) {
            addCriterion("fee not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andPayStsIsNull() {
            addCriterion("pay_Sts is null");
            return (Criteria) this;
        }

        public Criteria andPayStsIsNotNull() {
            addCriterion("pay_Sts is not null");
            return (Criteria) this;
        }

        public Criteria andPayStsEqualTo(String value) {
            addCriterion("pay_Sts =", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsNotEqualTo(String value) {
            addCriterion("pay_Sts <>", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsGreaterThan(String value) {
            addCriterion("pay_Sts >", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsGreaterThanOrEqualTo(String value) {
            addCriterion("pay_Sts >=", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsLessThan(String value) {
            addCriterion("pay_Sts <", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsLessThanOrEqualTo(String value) {
            addCriterion("pay_Sts <=", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsLike(String value) {
            addCriterion("pay_Sts like", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsNotLike(String value) {
            addCriterion("pay_Sts not like", value, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsIn(List<String> values) {
            addCriterion("pay_Sts in", values, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsNotIn(List<String> values) {
            addCriterion("pay_Sts not in", values, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsBetween(String value1, String value2) {
            addCriterion("pay_Sts between", value1, value2, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayStsNotBetween(String value1, String value2) {
            addCriterion("pay_Sts not between", value1, value2, "paySts");
            return (Criteria) this;
        }

        public Criteria andPayDtIsNull() {
            addCriterion("pay_Dt is null");
            return (Criteria) this;
        }

        public Criteria andPayDtIsNotNull() {
            addCriterion("pay_Dt is not null");
            return (Criteria) this;
        }

        public Criteria andPayDtEqualTo(String value) {
            addCriterion("pay_Dt =", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtNotEqualTo(String value) {
            addCriterion("pay_Dt <>", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtGreaterThan(String value) {
            addCriterion("pay_Dt >", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtGreaterThanOrEqualTo(String value) {
            addCriterion("pay_Dt >=", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtLessThan(String value) {
            addCriterion("pay_Dt <", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtLessThanOrEqualTo(String value) {
            addCriterion("pay_Dt <=", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtLike(String value) {
            addCriterion("pay_Dt like", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtNotLike(String value) {
            addCriterion("pay_Dt not like", value, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtIn(List<String> values) {
            addCriterion("pay_Dt in", values, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtNotIn(List<String> values) {
            addCriterion("pay_Dt not in", values, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtBetween(String value1, String value2) {
            addCriterion("pay_Dt between", value1, value2, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayDtNotBetween(String value1, String value2) {
            addCriterion("pay_Dt not between", value1, value2, "payDt");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("pay_Time is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("pay_Time is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(String value) {
            addCriterion("pay_Time =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(String value) {
            addCriterion("pay_Time <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(String value) {
            addCriterion("pay_Time >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(String value) {
            addCriterion("pay_Time >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(String value) {
            addCriterion("pay_Time <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(String value) {
            addCriterion("pay_Time <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLike(String value) {
            addCriterion("pay_Time like", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotLike(String value) {
            addCriterion("pay_Time not like", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<String> values) {
            addCriterion("pay_Time in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<String> values) {
            addCriterion("pay_Time not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(String value1, String value2) {
            addCriterion("pay_Time between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(String value1, String value2) {
            addCriterion("pay_Time not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andHmacIsNull() {
            addCriterion("hmac is null");
            return (Criteria) this;
        }

        public Criteria andHmacIsNotNull() {
            addCriterion("hmac is not null");
            return (Criteria) this;
        }

        public Criteria andHmacEqualTo(String value) {
            addCriterion("hmac =", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacNotEqualTo(String value) {
            addCriterion("hmac <>", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacGreaterThan(String value) {
            addCriterion("hmac >", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacGreaterThanOrEqualTo(String value) {
            addCriterion("hmac >=", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacLessThan(String value) {
            addCriterion("hmac <", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacLessThanOrEqualTo(String value) {
            addCriterion("hmac <=", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacLike(String value) {
            addCriterion("hmac like", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacNotLike(String value) {
            addCriterion("hmac not like", value, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacIn(List<String> values) {
            addCriterion("hmac in", values, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacNotIn(List<String> values) {
            addCriterion("hmac not in", values, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacBetween(String value1, String value2) {
            addCriterion("hmac between", value1, value2, "hmac");
            return (Criteria) this;
        }

        public Criteria andHmacNotBetween(String value1, String value2) {
            addCriterion("hmac not between", value1, value2, "hmac");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIsNull() {
            addCriterion("return_Code is null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIsNotNull() {
            addCriterion("return_Code is not null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeEqualTo(String value) {
            addCriterion("return_Code =", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotEqualTo(String value) {
            addCriterion("return_Code <>", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeGreaterThan(String value) {
            addCriterion("return_Code >", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("return_Code >=", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLessThan(String value) {
            addCriterion("return_Code <", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLessThanOrEqualTo(String value) {
            addCriterion("return_Code <=", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLike(String value) {
            addCriterion("return_Code like", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotLike(String value) {
            addCriterion("return_Code not like", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIn(List<String> values) {
            addCriterion("return_Code in", values, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotIn(List<String> values) {
            addCriterion("return_Code not in", values, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeBetween(String value1, String value2) {
            addCriterion("return_Code between", value1, value2, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotBetween(String value1, String value2) {
            addCriterion("return_Code not between", value1, value2, "returnCode");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andZyx1IsNull() {
            addCriterion("zyx1 is null");
            return (Criteria) this;
        }

        public Criteria andZyx1IsNotNull() {
            addCriterion("zyx1 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx1EqualTo(Integer value) {
            addCriterion("zyx1 =", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1NotEqualTo(Integer value) {
            addCriterion("zyx1 <>", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1GreaterThan(Integer value) {
            addCriterion("zyx1 >", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1GreaterThanOrEqualTo(Integer value) {
            addCriterion("zyx1 >=", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1LessThan(Integer value) {
            addCriterion("zyx1 <", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1LessThanOrEqualTo(Integer value) {
            addCriterion("zyx1 <=", value, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1In(List<Integer> values) {
            addCriterion("zyx1 in", values, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1NotIn(List<Integer> values) {
            addCriterion("zyx1 not in", values, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1Between(Integer value1, Integer value2) {
            addCriterion("zyx1 between", value1, value2, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx1NotBetween(Integer value1, Integer value2) {
            addCriterion("zyx1 not between", value1, value2, "zyx1");
            return (Criteria) this;
        }

        public Criteria andZyx2IsNull() {
            addCriterion("zyx2 is null");
            return (Criteria) this;
        }

        public Criteria andZyx2IsNotNull() {
            addCriterion("zyx2 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx2EqualTo(String value) {
            addCriterion("zyx2 =", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotEqualTo(String value) {
            addCriterion("zyx2 <>", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2GreaterThan(String value) {
            addCriterion("zyx2 >", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2GreaterThanOrEqualTo(String value) {
            addCriterion("zyx2 >=", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2LessThan(String value) {
            addCriterion("zyx2 <", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2LessThanOrEqualTo(String value) {
            addCriterion("zyx2 <=", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2Like(String value) {
            addCriterion("zyx2 like", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotLike(String value) {
            addCriterion("zyx2 not like", value, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2In(List<String> values) {
            addCriterion("zyx2 in", values, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotIn(List<String> values) {
            addCriterion("zyx2 not in", values, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2Between(String value1, String value2) {
            addCriterion("zyx2 between", value1, value2, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx2NotBetween(String value1, String value2) {
            addCriterion("zyx2 not between", value1, value2, "zyx2");
            return (Criteria) this;
        }

        public Criteria andZyx3IsNull() {
            addCriterion("zyx3 is null");
            return (Criteria) this;
        }

        public Criteria andZyx3IsNotNull() {
            addCriterion("zyx3 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx3EqualTo(String value) {
            addCriterion("zyx3 =", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotEqualTo(String value) {
            addCriterion("zyx3 <>", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3GreaterThan(String value) {
            addCriterion("zyx3 >", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3GreaterThanOrEqualTo(String value) {
            addCriterion("zyx3 >=", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3LessThan(String value) {
            addCriterion("zyx3 <", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3LessThanOrEqualTo(String value) {
            addCriterion("zyx3 <=", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3Like(String value) {
            addCriterion("zyx3 like", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotLike(String value) {
            addCriterion("zyx3 not like", value, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3In(List<String> values) {
            addCriterion("zyx3 in", values, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotIn(List<String> values) {
            addCriterion("zyx3 not in", values, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3Between(String value1, String value2) {
            addCriterion("zyx3 between", value1, value2, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx3NotBetween(String value1, String value2) {
            addCriterion("zyx3 not between", value1, value2, "zyx3");
            return (Criteria) this;
        }

        public Criteria andZyx4IsNull() {
            addCriterion("zyx4 is null");
            return (Criteria) this;
        }

        public Criteria andZyx4IsNotNull() {
            addCriterion("zyx4 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx4EqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 =", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4NotEqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 <>", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4GreaterThan(Date value) {
            addCriterionForJDBCDate("zyx4 >", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 >=", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4LessThan(Date value) {
            addCriterionForJDBCDate("zyx4 <", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("zyx4 <=", value, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4In(List<Date> values) {
            addCriterionForJDBCDate("zyx4 in", values, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4NotIn(List<Date> values) {
            addCriterionForJDBCDate("zyx4 not in", values, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4Between(Date value1, Date value2) {
            addCriterionForJDBCDate("zyx4 between", value1, value2, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx4NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("zyx4 not between", value1, value2, "zyx4");
            return (Criteria) this;
        }

        public Criteria andZyx5IsNull() {
            addCriterion("zyx5 is null");
            return (Criteria) this;
        }

        public Criteria andZyx5IsNotNull() {
            addCriterion("zyx5 is not null");
            return (Criteria) this;
        }

        public Criteria andZyx5EqualTo(BigDecimal value) {
            addCriterion("zyx5 =", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5NotEqualTo(BigDecimal value) {
            addCriterion("zyx5 <>", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5GreaterThan(BigDecimal value) {
            addCriterion("zyx5 >", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("zyx5 >=", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5LessThan(BigDecimal value) {
            addCriterion("zyx5 <", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("zyx5 <=", value, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5In(List<BigDecimal> values) {
            addCriterion("zyx5 in", values, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5NotIn(List<BigDecimal> values) {
            addCriterion("zyx5 not in", values, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("zyx5 between", value1, value2, "zyx5");
            return (Criteria) this;
        }

        public Criteria andZyx5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zyx5 not between", value1, value2, "zyx5");
            return (Criteria) this;
        }

        public Criteria andMercIdIsNull() {
            addCriterion("merc_Id is null");
            return (Criteria) this;
        }

        public Criteria andMercIdIsNotNull() {
            addCriterion("merc_Id is not null");
            return (Criteria) this;
        }

        public Criteria andMercIdEqualTo(String value) {
            addCriterion("merc_Id =", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdNotEqualTo(String value) {
            addCriterion("merc_Id <>", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdGreaterThan(String value) {
            addCriterion("merc_Id >", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdGreaterThanOrEqualTo(String value) {
            addCriterion("merc_Id >=", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdLessThan(String value) {
            addCriterion("merc_Id <", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdLessThanOrEqualTo(String value) {
            addCriterion("merc_Id <=", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdLike(String value) {
            addCriterion("merc_Id like", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdNotLike(String value) {
            addCriterion("merc_Id not like", value, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdIn(List<String> values) {
            addCriterion("merc_Id in", values, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdNotIn(List<String> values) {
            addCriterion("merc_Id not in", values, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdBetween(String value1, String value2) {
            addCriterion("merc_Id between", value1, value2, "mercId");
            return (Criteria) this;
        }

        public Criteria andMercIdNotBetween(String value1, String value2) {
            addCriterion("merc_Id not between", value1, value2, "mercId");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNull() {
            addCriterion("sign_Type is null");
            return (Criteria) this;
        }

        public Criteria andSignTypeIsNotNull() {
            addCriterion("sign_Type is not null");
            return (Criteria) this;
        }

        public Criteria andSignTypeEqualTo(String value) {
            addCriterion("sign_Type =", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotEqualTo(String value) {
            addCriterion("sign_Type <>", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThan(String value) {
            addCriterion("sign_Type >", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sign_Type >=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThan(String value) {
            addCriterion("sign_Type <", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLessThanOrEqualTo(String value) {
            addCriterion("sign_Type <=", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeLike(String value) {
            addCriterion("sign_Type like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotLike(String value) {
            addCriterion("sign_Type not like", value, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeIn(List<String> values) {
            addCriterion("sign_Type in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotIn(List<String> values) {
            addCriterion("sign_Type not in", values, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeBetween(String value1, String value2) {
            addCriterion("sign_Type between", value1, value2, "signType");
            return (Criteria) this;
        }

        public Criteria andSignTypeNotBetween(String value1, String value2) {
            addCriterion("sign_Type not between", value1, value2, "signType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_result
     *
     * @mbggenerated do_not_delete_during_merge Fri Nov 13 17:44:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_result
     *
     * @mbggenerated Fri Nov 13 17:44:58 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}