package com.dsh.m.model;

import java.util.ArrayList;
import java.util.List;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Iterator;

public class SupplyCustomerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected int limitStart = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected int limitEnd = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public SupplyCustomerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andSCidIsNull() {
			addCriterion("s_cid is null");
			return (Criteria) this;
		}

		public Criteria andSCidIsNotNull() {
			addCriterion("s_cid is not null");
			return (Criteria) this;
		}

		public Criteria andSCidEqualTo(Integer value) {
			addCriterion("s_cid =", value, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidNotEqualTo(Integer value) {
			addCriterion("s_cid <>", value, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidGreaterThan(Integer value) {
			addCriterion("s_cid >", value, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidGreaterThanOrEqualTo(Integer value) {
			addCriterion("s_cid >=", value, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidLessThan(Integer value) {
			addCriterion("s_cid <", value, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidLessThanOrEqualTo(Integer value) {
			addCriterion("s_cid <=", value, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidIn(List<Integer> values) {
			addCriterion("s_cid in", values, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidNotIn(List<Integer> values) {
			addCriterion("s_cid not in", values, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidBetween(Integer value1, Integer value2) {
			addCriterion("s_cid between", value1, value2, "sCid");
			return (Criteria) this;
		}

		public Criteria andSCidNotBetween(Integer value1, Integer value2) {
			addCriterion("s_cid not between", value1, value2, "sCid");
			return (Criteria) this;
		}

		public Criteria andSupplyidIsNull() {
			addCriterion("supplyid is null");
			return (Criteria) this;
		}

		public Criteria andSupplyidIsNotNull() {
			addCriterion("supplyid is not null");
			return (Criteria) this;
		}

		public Criteria andSupplyidEqualTo(Integer value) {
			addCriterion("supplyid =", value, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidNotEqualTo(Integer value) {
			addCriterion("supplyid <>", value, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidGreaterThan(Integer value) {
			addCriterion("supplyid >", value, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidGreaterThanOrEqualTo(Integer value) {
			addCriterion("supplyid >=", value, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidLessThan(Integer value) {
			addCriterion("supplyid <", value, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidLessThanOrEqualTo(Integer value) {
			addCriterion("supplyid <=", value, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidIn(List<Integer> values) {
			addCriterion("supplyid in", values, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidNotIn(List<Integer> values) {
			addCriterion("supplyid not in", values, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidBetween(Integer value1, Integer value2) {
			addCriterion("supplyid between", value1, value2, "supplyid");
			return (Criteria) this;
		}

		public Criteria andSupplyidNotBetween(Integer value1, Integer value2) {
			addCriterion("supplyid not between", value1, value2, "supplyid");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNull() {
			addCriterion("customerid is null");
			return (Criteria) this;
		}

		public Criteria andCustomeridIsNotNull() {
			addCriterion("customerid is not null");
			return (Criteria) this;
		}

		public Criteria andCustomeridEqualTo(Integer value) {
			addCriterion("customerid =", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotEqualTo(Integer value) {
			addCriterion("customerid <>", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThan(Integer value) {
			addCriterion("customerid >", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridGreaterThanOrEqualTo(Integer value) {
			addCriterion("customerid >=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThan(Integer value) {
			addCriterion("customerid <", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridLessThanOrEqualTo(Integer value) {
			addCriterion("customerid <=", value, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridIn(List<Integer> values) {
			addCriterion("customerid in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotIn(List<Integer> values) {
			addCriterion("customerid not in", values, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridBetween(Integer value1, Integer value2) {
			addCriterion("customerid between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andCustomeridNotBetween(Integer value1, Integer value2) {
			addCriterion("customerid not between", value1, value2, "customerid");
			return (Criteria) this;
		}

		public Criteria andExponentIsNull() {
			addCriterion("exponent is null");
			return (Criteria) this;
		}

		public Criteria andExponentIsNotNull() {
			addCriterion("exponent is not null");
			return (Criteria) this;
		}

		public Criteria andExponentEqualTo(Float value) {
			addCriterion("exponent =", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotEqualTo(Float value) {
			addCriterion("exponent <>", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentGreaterThan(Float value) {
			addCriterion("exponent >", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentGreaterThanOrEqualTo(Float value) {
			addCriterion("exponent >=", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentLessThan(Float value) {
			addCriterion("exponent <", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentLessThanOrEqualTo(Float value) {
			addCriterion("exponent <=", value, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentIn(List<Float> values) {
			addCriterion("exponent in", values, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotIn(List<Float> values) {
			addCriterion("exponent not in", values, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentBetween(Float value1, Float value2) {
			addCriterion("exponent between", value1, value2, "exponent");
			return (Criteria) this;
		}

		public Criteria andExponentNotBetween(Float value1, Float value2) {
			addCriterion("exponent not between", value1, value2, "exponent");
			return (Criteria) this;
		}

		public Criteria andDelivertimeIsNull() {
			addCriterion("delivertime is null");
			return (Criteria) this;
		}

		public Criteria andDelivertimeIsNotNull() {
			addCriterion("delivertime is not null");
			return (Criteria) this;
		}

		public Criteria andDelivertimeEqualTo(String value) {
			addCriterion("delivertime =", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeNotEqualTo(String value) {
			addCriterion("delivertime <>", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeGreaterThan(String value) {
			addCriterion("delivertime >", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeGreaterThanOrEqualTo(String value) {
			addCriterion("delivertime >=", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeLessThan(String value) {
			addCriterion("delivertime <", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeLessThanOrEqualTo(String value) {
			addCriterion("delivertime <=", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeLike(String value) {
			addCriterion("delivertime like", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeNotLike(String value) {
			addCriterion("delivertime not like", value, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeIn(List<String> values) {
			addCriterion("delivertime in", values, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeNotIn(List<String> values) {
			addCriterion("delivertime not in", values, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeBetween(String value1, String value2) {
			addCriterion("delivertime between", value1, value2, "delivertime");
			return (Criteria) this;
		}

		public Criteria andDelivertimeNotBetween(String value1, String value2) {
			addCriterion("delivertime not between", value1, value2,
					"delivertime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeIsNull() {
			addCriterion("agreement_starttime is null");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeIsNotNull() {
			addCriterion("agreement_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeEqualTo(Date value) {
			addCriterion("agreement_starttime =", value, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeNotEqualTo(Date value) {
			addCriterion("agreement_starttime <>", value, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeGreaterThan(Date value) {
			addCriterion("agreement_starttime >", value, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("agreement_starttime >=", value, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeLessThan(Date value) {
			addCriterion("agreement_starttime <", value, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeLessThanOrEqualTo(Date value) {
			addCriterion("agreement_starttime <=", value, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeIn(List<Date> values) {
			addCriterion("agreement_starttime in", values, "agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeNotIn(List<Date> values) {
			addCriterion("agreement_starttime not in", values,
					"agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeBetween(Date value1, Date value2) {
			addCriterion("agreement_starttime between", value1, value2,
					"agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementStarttimeNotBetween(Date value1, Date value2) {
			addCriterion("agreement_starttime not between", value1, value2,
					"agreementStarttime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeIsNull() {
			addCriterion("agreement_endtime is null");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeIsNotNull() {
			addCriterion("agreement_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeEqualTo(Date value) {
			addCriterion("agreement_endtime =", value, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeNotEqualTo(Date value) {
			addCriterion("agreement_endtime <>", value, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeGreaterThan(Date value) {
			addCriterion("agreement_endtime >", value, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("agreement_endtime >=", value, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeLessThan(Date value) {
			addCriterion("agreement_endtime <", value, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeLessThanOrEqualTo(Date value) {
			addCriterion("agreement_endtime <=", value, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeIn(List<Date> values) {
			addCriterion("agreement_endtime in", values, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeNotIn(List<Date> values) {
			addCriterion("agreement_endtime not in", values, "agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeBetween(Date value1, Date value2) {
			addCriterion("agreement_endtime between", value1, value2,
					"agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andAgreementEndtimeNotBetween(Date value1, Date value2) {
			addCriterion("agreement_endtime not between", value1, value2,
					"agreementEndtime");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteIsNull() {
			addCriterion("distribution_route is null");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteIsNotNull() {
			addCriterion("distribution_route is not null");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteEqualTo(Integer value) {
			addCriterion("distribution_route =", value, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteNotEqualTo(Integer value) {
			addCriterion("distribution_route <>", value, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteGreaterThan(Integer value) {
			addCriterion("distribution_route >", value, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteGreaterThanOrEqualTo(Integer value) {
			addCriterion("distribution_route >=", value, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteLessThan(Integer value) {
			addCriterion("distribution_route <", value, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteLessThanOrEqualTo(Integer value) {
			addCriterion("distribution_route <=", value, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteIn(List<Integer> values) {
			addCriterion("distribution_route in", values, "distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteNotIn(List<Integer> values) {
			addCriterion("distribution_route not in", values,
					"distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteBetween(Integer value1,
				Integer value2) {
			addCriterion("distribution_route between", value1, value2,
					"distributionRoute");
			return (Criteria) this;
		}

		public Criteria andDistributionRouteNotBetween(Integer value1,
				Integer value2) {
			addCriterion("distribution_route not between", value1, value2,
					"distributionRoute");
			return (Criteria) this;
		}

		public Criteria andAgreementnumIsNull() {
			addCriterion("agreementnum is null");
			return (Criteria) this;
		}

		public Criteria andAgreementnumIsNotNull() {
			addCriterion("agreementnum is not null");
			return (Criteria) this;
		}

		public Criteria andAgreementnumEqualTo(String value) {
			addCriterion("agreementnum =", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumNotEqualTo(String value) {
			addCriterion("agreementnum <>", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumGreaterThan(String value) {
			addCriterion("agreementnum >", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumGreaterThanOrEqualTo(String value) {
			addCriterion("agreementnum >=", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumLessThan(String value) {
			addCriterion("agreementnum <", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumLessThanOrEqualTo(String value) {
			addCriterion("agreementnum <=", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumLike(String value) {
			addCriterion("agreementnum like", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumNotLike(String value) {
			addCriterion("agreementnum not like", value, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumIn(List<String> values) {
			addCriterion("agreementnum in", values, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumNotIn(List<String> values) {
			addCriterion("agreementnum not in", values, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumBetween(String value1, String value2) {
			addCriterion("agreementnum between", value1, value2, "agreementnum");
			return (Criteria) this;
		}

		public Criteria andAgreementnumNotBetween(String value1, String value2) {
			addCriterion("agreementnum not between", value1, value2,
					"agreementnum");
			return (Criteria) this;
		}

		public Criteria andClassifyIsNull() {
			addCriterion("classify is null");
			return (Criteria) this;
		}

		public Criteria andClassifyIsNotNull() {
			addCriterion("classify is not null");
			return (Criteria) this;
		}

		public Criteria andClassifyEqualTo(Integer value) {
			addCriterion("classify =", value, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyNotEqualTo(Integer value) {
			addCriterion("classify <>", value, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyGreaterThan(Integer value) {
			addCriterion("classify >", value, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyGreaterThanOrEqualTo(Integer value) {
			addCriterion("classify >=", value, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyLessThan(Integer value) {
			addCriterion("classify <", value, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyLessThanOrEqualTo(Integer value) {
			addCriterion("classify <=", value, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyIn(List<Integer> values) {
			addCriterion("classify in", values, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyNotIn(List<Integer> values) {
			addCriterion("classify not in", values, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyBetween(Integer value1, Integer value2) {
			addCriterion("classify between", value1, value2, "classify");
			return (Criteria) this;
		}

		public Criteria andClassifyNotBetween(Integer value1, Integer value2) {
			addCriterion("classify not between", value1, value2, "classify");
			return (Criteria) this;
		}

		public Criteria andSortnoIsNull() {
			addCriterion("sortno is null");
			return (Criteria) this;
		}

		public Criteria andSortnoIsNotNull() {
			addCriterion("sortno is not null");
			return (Criteria) this;
		}

		public Criteria andSortnoEqualTo(Short value) {
			addCriterion("sortno =", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotEqualTo(Short value) {
			addCriterion("sortno <>", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoGreaterThan(Short value) {
			addCriterion("sortno >", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoGreaterThanOrEqualTo(Short value) {
			addCriterion("sortno >=", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoLessThan(Short value) {
			addCriterion("sortno <", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoLessThanOrEqualTo(Short value) {
			addCriterion("sortno <=", value, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoIn(List<Short> values) {
			addCriterion("sortno in", values, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotIn(List<Short> values) {
			addCriterion("sortno not in", values, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoBetween(Short value1, Short value2) {
			addCriterion("sortno between", value1, value2, "sortno");
			return (Criteria) this;
		}

		public Criteria andSortnoNotBetween(Short value1, Short value2) {
			addCriterion("sortno not between", value1, value2, "sortno");
			return (Criteria) this;
		}

		public Criteria andCommntIsNull() {
			addCriterion("commnt is null");
			return (Criteria) this;
		}

		public Criteria andCommntIsNotNull() {
			addCriterion("commnt is not null");
			return (Criteria) this;
		}

		public Criteria andCommntEqualTo(String value) {
			addCriterion("commnt =", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntNotEqualTo(String value) {
			addCriterion("commnt <>", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntGreaterThan(String value) {
			addCriterion("commnt >", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntGreaterThanOrEqualTo(String value) {
			addCriterion("commnt >=", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntLessThan(String value) {
			addCriterion("commnt <", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntLessThanOrEqualTo(String value) {
			addCriterion("commnt <=", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntLike(String value) {
			addCriterion("commnt like", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntNotLike(String value) {
			addCriterion("commnt not like", value, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntIn(List<String> values) {
			addCriterion("commnt in", values, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntNotIn(List<String> values) {
			addCriterion("commnt not in", values, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntBetween(String value1, String value2) {
			addCriterion("commnt between", value1, value2, "commnt");
			return (Criteria) this;
		}

		public Criteria andCommntNotBetween(String value1, String value2) {
			addCriterion("commnt not between", value1, value2, "commnt");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("create_user is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("create_user is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserEqualTo(Integer value) {
			addCriterion("create_user =", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotEqualTo(Integer value) {
			addCriterion("create_user <>", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThan(Integer value) {
			addCriterion("create_user >", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_user >=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThan(Integer value) {
			addCriterion("create_user <", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
			addCriterion("create_user <=", value, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserIn(List<Integer> values) {
			addCriterion("create_user in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotIn(List<Integer> values) {
			addCriterion("create_user not in", values, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserBetween(Integer value1, Integer value2) {
			addCriterion("create_user between", value1, value2, "createUser");
			return (Criteria) this;
		}

		public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
			addCriterion("create_user not between", value1, value2,
					"createUser");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(Integer value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(Integer value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(Integer value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(Integer value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<Integer> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<Integer> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
			addCriterion("update_user not between", value1, value2,
					"updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andTsIsNull() {
			addCriterion("ts is null");
			return (Criteria) this;
		}

		public Criteria andTsIsNotNull() {
			addCriterion("ts is not null");
			return (Criteria) this;
		}

		public Criteria andTsEqualTo(String value) {
			addCriterion("ts =", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotEqualTo(String value) {
			addCriterion("ts <>", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsGreaterThan(String value) {
			addCriterion("ts >", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsGreaterThanOrEqualTo(String value) {
			addCriterion("ts >=", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsLessThan(String value) {
			addCriterion("ts <", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsLessThanOrEqualTo(String value) {
			addCriterion("ts <=", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsLike(String value) {
			addCriterion("ts like", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotLike(String value) {
			addCriterion("ts not like", value, "ts");
			return (Criteria) this;
		}

		public Criteria andTsIn(List<String> values) {
			addCriterion("ts in", values, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotIn(List<String> values) {
			addCriterion("ts not in", values, "ts");
			return (Criteria) this;
		}

		public Criteria andTsBetween(String value1, String value2) {
			addCriterion("ts between", value1, value2, "ts");
			return (Criteria) this;
		}

		public Criteria andTsNotBetween(String value1, String value2) {
			addCriterion("ts not between", value1, value2, "ts");
			return (Criteria) this;
		}

		public Criteria andDrIsNull() {
			addCriterion("dr is null");
			return (Criteria) this;
		}

		public Criteria andDrIsNotNull() {
			addCriterion("dr is not null");
			return (Criteria) this;
		}

		public Criteria andDrEqualTo(String value) {
			addCriterion("dr =", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrNotEqualTo(String value) {
			addCriterion("dr <>", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrGreaterThan(String value) {
			addCriterion("dr >", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrGreaterThanOrEqualTo(String value) {
			addCriterion("dr >=", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrLessThan(String value) {
			addCriterion("dr <", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrLessThanOrEqualTo(String value) {
			addCriterion("dr <=", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrLike(String value) {
			addCriterion("dr like", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrNotLike(String value) {
			addCriterion("dr not like", value, "dr");
			return (Criteria) this;
		}

		public Criteria andDrIn(List<String> values) {
			addCriterion("dr in", values, "dr");
			return (Criteria) this;
		}

		public Criteria andDrNotIn(List<String> values) {
			addCriterion("dr not in", values, "dr");
			return (Criteria) this;
		}

		public Criteria andDrBetween(String value1, String value2) {
			addCriterion("dr between", value1, value2, "dr");
			return (Criteria) this;
		}

		public Criteria andDrNotBetween(String value1, String value2) {
			addCriterion("dr not between", value1, value2, "dr");
			return (Criteria) this;
		}

		public Criteria andZyx1IsNull() {
			addCriterion("zyx1 is null");
			return (Criteria) this;
		}

		public Criteria andZyx1IsNotNull() {
			addCriterion("zyx1 is not null");
			return (Criteria) this;
		}

		public Criteria andZyx1EqualTo(Integer value) {
			addCriterion("zyx1 =", value, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1NotEqualTo(Integer value) {
			addCriterion("zyx1 <>", value, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1GreaterThan(Integer value) {
			addCriterion("zyx1 >", value, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1GreaterThanOrEqualTo(Integer value) {
			addCriterion("zyx1 >=", value, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1LessThan(Integer value) {
			addCriterion("zyx1 <", value, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1LessThanOrEqualTo(Integer value) {
			addCriterion("zyx1 <=", value, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1In(List<Integer> values) {
			addCriterion("zyx1 in", values, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1NotIn(List<Integer> values) {
			addCriterion("zyx1 not in", values, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1Between(Integer value1, Integer value2) {
			addCriterion("zyx1 between", value1, value2, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx1NotBetween(Integer value1, Integer value2) {
			addCriterion("zyx1 not between", value1, value2, "zyx1");
			return (Criteria) this;
		}

		public Criteria andZyx2IsNull() {
			addCriterion("zyx2 is null");
			return (Criteria) this;
		}

		public Criteria andZyx2IsNotNull() {
			addCriterion("zyx2 is not null");
			return (Criteria) this;
		}

		public Criteria andZyx2EqualTo(String value) {
			addCriterion("zyx2 =", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2NotEqualTo(String value) {
			addCriterion("zyx2 <>", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2GreaterThan(String value) {
			addCriterion("zyx2 >", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2GreaterThanOrEqualTo(String value) {
			addCriterion("zyx2 >=", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2LessThan(String value) {
			addCriterion("zyx2 <", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2LessThanOrEqualTo(String value) {
			addCriterion("zyx2 <=", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2Like(String value) {
			addCriterion("zyx2 like", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2NotLike(String value) {
			addCriterion("zyx2 not like", value, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2In(List<String> values) {
			addCriterion("zyx2 in", values, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2NotIn(List<String> values) {
			addCriterion("zyx2 not in", values, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2Between(String value1, String value2) {
			addCriterion("zyx2 between", value1, value2, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx2NotBetween(String value1, String value2) {
			addCriterion("zyx2 not between", value1, value2, "zyx2");
			return (Criteria) this;
		}

		public Criteria andZyx3IsNull() {
			addCriterion("zyx3 is null");
			return (Criteria) this;
		}

		public Criteria andZyx3IsNotNull() {
			addCriterion("zyx3 is not null");
			return (Criteria) this;
		}

		public Criteria andZyx3EqualTo(String value) {
			addCriterion("zyx3 =", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3NotEqualTo(String value) {
			addCriterion("zyx3 <>", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3GreaterThan(String value) {
			addCriterion("zyx3 >", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3GreaterThanOrEqualTo(String value) {
			addCriterion("zyx3 >=", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3LessThan(String value) {
			addCriterion("zyx3 <", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3LessThanOrEqualTo(String value) {
			addCriterion("zyx3 <=", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3Like(String value) {
			addCriterion("zyx3 like", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3NotLike(String value) {
			addCriterion("zyx3 not like", value, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3In(List<String> values) {
			addCriterion("zyx3 in", values, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3NotIn(List<String> values) {
			addCriterion("zyx3 not in", values, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3Between(String value1, String value2) {
			addCriterion("zyx3 between", value1, value2, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx3NotBetween(String value1, String value2) {
			addCriterion("zyx3 not between", value1, value2, "zyx3");
			return (Criteria) this;
		}

		public Criteria andZyx4IsNull() {
			addCriterion("zyx4 is null");
			return (Criteria) this;
		}

		public Criteria andZyx4IsNotNull() {
			addCriterion("zyx4 is not null");
			return (Criteria) this;
		}

		public Criteria andZyx4EqualTo(Date value) {
			addCriterionForJDBCDate("zyx4 =", value, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4NotEqualTo(Date value) {
			addCriterionForJDBCDate("zyx4 <>", value, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4GreaterThan(Date value) {
			addCriterionForJDBCDate("zyx4 >", value, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4GreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("zyx4 >=", value, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4LessThan(Date value) {
			addCriterionForJDBCDate("zyx4 <", value, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4LessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("zyx4 <=", value, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4In(List<Date> values) {
			addCriterionForJDBCDate("zyx4 in", values, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4NotIn(List<Date> values) {
			addCriterionForJDBCDate("zyx4 not in", values, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4Between(Date value1, Date value2) {
			addCriterionForJDBCDate("zyx4 between", value1, value2, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx4NotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("zyx4 not between", value1, value2, "zyx4");
			return (Criteria) this;
		}

		public Criteria andZyx5IsNull() {
			addCriterion("zyx5 is null");
			return (Criteria) this;
		}

		public Criteria andZyx5IsNotNull() {
			addCriterion("zyx5 is not null");
			return (Criteria) this;
		}

		public Criteria andZyx5EqualTo(BigDecimal value) {
			addCriterion("zyx5 =", value, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5NotEqualTo(BigDecimal value) {
			addCriterion("zyx5 <>", value, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5GreaterThan(BigDecimal value) {
			addCriterion("zyx5 >", value, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("zyx5 >=", value, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5LessThan(BigDecimal value) {
			addCriterion("zyx5 <", value, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5LessThanOrEqualTo(BigDecimal value) {
			addCriterion("zyx5 <=", value, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5In(List<BigDecimal> values) {
			addCriterion("zyx5 in", values, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5NotIn(List<BigDecimal> values) {
			addCriterion("zyx5 not in", values, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("zyx5 between", value1, value2, "zyx5");
			return (Criteria) this;
		}

		public Criteria andZyx5NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("zyx5 not between", value1, value2, "zyx5");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table supply_customer
	 * @mbggenerated  Wed Oct 21 10:19:18 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supply_customer
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 27 12:12:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}