package com.dsh.m.model;

public class SupplyCustomer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply_customer.s_cid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer sCid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply_customer.supplyid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer supplyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply_customer.customerid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply_customer.exponent
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Float exponent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply_customer.delivertime
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String delivertime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply_customer.s_cid
	 * @return  the value of supply_customer.s_cid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getsCid() {
		return sCid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply_customer.s_cid
	 * @param sCid  the value for supply_customer.s_cid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setsCid(Integer sCid) {
		this.sCid = sCid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply_customer.supplyid
	 * @return  the value of supply_customer.supplyid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getSupplyid() {
		return supplyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply_customer.supplyid
	 * @param supplyid  the value for supply_customer.supplyid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSupplyid(Integer supplyid) {
		this.supplyid = supplyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply_customer.customerid
	 * @return  the value of supply_customer.customerid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply_customer.customerid
	 * @param customerid  the value for supply_customer.customerid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply_customer.exponent
	 * @return  the value of supply_customer.exponent
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Float getExponent() {
		return exponent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply_customer.exponent
	 * @param exponent  the value for supply_customer.exponent
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setExponent(Float exponent) {
		this.exponent = exponent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply_customer.delivertime
	 * @return  the value of supply_customer.delivertime
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDelivertime() {
		return delivertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply_customer.delivertime
	 * @param delivertime  the value for supply_customer.delivertime
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDelivertime(String delivertime) {
		this.delivertime = delivertime;
	}
}