package com.dsh.m.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Supply implements Serializable {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.supplyid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer supplyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.username
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.sex
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.age
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.edu
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String edu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.identity
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String identity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.telephone
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.mobile
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.qq
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.email
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.other
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String other;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.shopname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String shopname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.shortname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String shortname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.addr
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.capability
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String capability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.sign_begin
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Date signBegin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.sign_end
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Date signEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.loginname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String loginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.loginpass
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String loginpass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.status
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.register_time
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.deal_pool
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private BigDecimal dealPool;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.rolesid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer rolesid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.subareaid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer subareaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.bclassid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer bclassid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.subSell
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String subsell;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.DistributeTime
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String distributetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.DistributeArea
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String distributearea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.speciallGoods
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String speciallgoods;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.DistributeDemand
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String distributedemand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.dosaingComments
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String dosaingcomments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.isRecommend
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer isrecommend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supply.telautogram
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String telautogram;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.supplyid
	 * @return  the value of supply.supplyid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getSupplyid() {
		return supplyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.supplyid
	 * @param supplyid  the value for supply.supplyid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSupplyid(Integer supplyid) {
		this.supplyid = supplyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.username
	 * @return  the value of supply.username
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.username
	 * @param username  the value for supply.username
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.sex
	 * @return  the value of supply.sex
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.sex
	 * @param sex  the value for supply.sex
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.age
	 * @return  the value of supply.age
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.age
	 * @param age  the value for supply.age
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setAge(String age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.edu
	 * @return  the value of supply.edu
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getEdu() {
		return edu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.edu
	 * @param edu  the value for supply.edu
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setEdu(String edu) {
		this.edu = edu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.identity
	 * @return  the value of supply.identity
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getIdentity() {
		return identity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.identity
	 * @param identity  the value for supply.identity
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setIdentity(String identity) {
		this.identity = identity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.telephone
	 * @return  the value of supply.telephone
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.telephone
	 * @param telephone  the value for supply.telephone
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.mobile
	 * @return  the value of supply.mobile
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.mobile
	 * @param mobile  the value for supply.mobile
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.qq
	 * @return  the value of supply.qq
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.qq
	 * @param qq  the value for supply.qq
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.email
	 * @return  the value of supply.email
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.email
	 * @param email  the value for supply.email
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.other
	 * @return  the value of supply.other
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getOther() {
		return other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.other
	 * @param other  the value for supply.other
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setOther(String other) {
		this.other = other;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.shopname
	 * @return  the value of supply.shopname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getShopname() {
		return shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.shopname
	 * @param shopname  the value for supply.shopname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.shortname
	 * @return  the value of supply.shortname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getShortname() {
		return shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.shortname
	 * @param shortname  the value for supply.shortname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.addr
	 * @return  the value of supply.addr
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.addr
	 * @param addr  the value for supply.addr
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.capability
	 * @return  the value of supply.capability
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getCapability() {
		return capability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.capability
	 * @param capability  the value for supply.capability
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setCapability(String capability) {
		this.capability = capability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.sign_begin
	 * @return  the value of supply.sign_begin
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Date getSignBegin() {
		return signBegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.sign_begin
	 * @param signBegin  the value for supply.sign_begin
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSignBegin(Date signBegin) {
		this.signBegin = signBegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.sign_end
	 * @return  the value of supply.sign_end
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Date getSignEnd() {
		return signEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.sign_end
	 * @param signEnd  the value for supply.sign_end
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSignEnd(Date signEnd) {
		this.signEnd = signEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.loginname
	 * @return  the value of supply.loginname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.loginname
	 * @param loginname  the value for supply.loginname
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.loginpass
	 * @return  the value of supply.loginpass
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getLoginpass() {
		return loginpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.loginpass
	 * @param loginpass  the value for supply.loginpass
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setLoginpass(String loginpass) {
		this.loginpass = loginpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.status
	 * @return  the value of supply.status
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.status
	 * @param status  the value for supply.status
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.register_time
	 * @return  the value of supply.register_time
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.register_time
	 * @param registerTime  the value for supply.register_time
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.deal_pool
	 * @return  the value of supply.deal_pool
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public BigDecimal getDealPool() {
		return dealPool;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.deal_pool
	 * @param dealPool  the value for supply.deal_pool
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDealPool(BigDecimal dealPool) {
		this.dealPool = dealPool;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.rolesid
	 * @return  the value of supply.rolesid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getRolesid() {
		return rolesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.rolesid
	 * @param rolesid  the value for supply.rolesid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setRolesid(Integer rolesid) {
		this.rolesid = rolesid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.subareaid
	 * @return  the value of supply.subareaid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getSubareaid() {
		return subareaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.subareaid
	 * @param subareaid  the value for supply.subareaid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSubareaid(Integer subareaid) {
		this.subareaid = subareaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.bclassid
	 * @return  the value of supply.bclassid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getBclassid() {
		return bclassid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.bclassid
	 * @param bclassid  the value for supply.bclassid
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setBclassid(Integer bclassid) {
		this.bclassid = bclassid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.subSell
	 * @return  the value of supply.subSell
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getSubsell() {
		return subsell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.subSell
	 * @param subsell  the value for supply.subSell
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSubsell(String subsell) {
		this.subsell = subsell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.DistributeTime
	 * @return  the value of supply.DistributeTime
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDistributetime() {
		return distributetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.DistributeTime
	 * @param distributetime  the value for supply.DistributeTime
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDistributetime(String distributetime) {
		this.distributetime = distributetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.DistributeArea
	 * @return  the value of supply.DistributeArea
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDistributearea() {
		return distributearea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.DistributeArea
	 * @param distributearea  the value for supply.DistributeArea
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDistributearea(String distributearea) {
		this.distributearea = distributearea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.speciallGoods
	 * @return  the value of supply.speciallGoods
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getSpeciallgoods() {
		return speciallgoods;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.speciallGoods
	 * @param speciallgoods  the value for supply.speciallGoods
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setSpeciallgoods(String speciallgoods) {
		this.speciallgoods = speciallgoods;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.DistributeDemand
	 * @return  the value of supply.DistributeDemand
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDistributedemand() {
		return distributedemand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.DistributeDemand
	 * @param distributedemand  the value for supply.DistributeDemand
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDistributedemand(String distributedemand) {
		this.distributedemand = distributedemand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.dosaingComments
	 * @return  the value of supply.dosaingComments
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDosaingcomments() {
		return dosaingcomments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.dosaingComments
	 * @param dosaingcomments  the value for supply.dosaingComments
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDosaingcomments(String dosaingcomments) {
		this.dosaingcomments = dosaingcomments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.isRecommend
	 * @return  the value of supply.isRecommend
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getIsrecommend() {
		return isrecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.isRecommend
	 * @param isrecommend  the value for supply.isRecommend
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setIsrecommend(Integer isrecommend) {
		this.isrecommend = isrecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supply.telautogram
	 * @return  the value of supply.telautogram
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getTelautogram() {
		return telautogram;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supply.telautogram
	 * @param telautogram  the value for supply.telautogram
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setTelautogram(String telautogram) {
		this.telautogram = telautogram;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -8160280243912991544L;
}