package com.dsh.m.model;

public class SysDictype {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.id
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.dictype
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String dictype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.name
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.type
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.memo
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.ts
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String ts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.dr
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String dr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.zdy1
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String zdy1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.zdy2
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String zdy2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.zdy3
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String zdy3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.zdy4
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String zdy4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dictype.zdy5
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	private String zdy5;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.id
	 * @return  the value of sys_dictype.id
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.id
	 * @param id  the value for sys_dictype.id
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.dictype
	 * @return  the value of sys_dictype.dictype
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDictype() {
		return dictype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.dictype
	 * @param dictype  the value for sys_dictype.dictype
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDictype(String dictype) {
		this.dictype = dictype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.name
	 * @return  the value of sys_dictype.name
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.name
	 * @param name  the value for sys_dictype.name
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.type
	 * @return  the value of sys_dictype.type
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.type
	 * @param type  the value for sys_dictype.type
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.memo
	 * @return  the value of sys_dictype.memo
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.memo
	 * @param memo  the value for sys_dictype.memo
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.ts
	 * @return  the value of sys_dictype.ts
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getTs() {
		return ts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.ts
	 * @param ts  the value for sys_dictype.ts
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setTs(String ts) {
		this.ts = ts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.dr
	 * @return  the value of sys_dictype.dr
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getDr() {
		return dr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.dr
	 * @param dr  the value for sys_dictype.dr
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setDr(String dr) {
		this.dr = dr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.zdy1
	 * @return  the value of sys_dictype.zdy1
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getZdy1() {
		return zdy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.zdy1
	 * @param zdy1  the value for sys_dictype.zdy1
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setZdy1(String zdy1) {
		this.zdy1 = zdy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.zdy2
	 * @return  the value of sys_dictype.zdy2
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getZdy2() {
		return zdy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.zdy2
	 * @param zdy2  the value for sys_dictype.zdy2
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setZdy2(String zdy2) {
		this.zdy2 = zdy2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.zdy3
	 * @return  the value of sys_dictype.zdy3
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getZdy3() {
		return zdy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.zdy3
	 * @param zdy3  the value for sys_dictype.zdy3
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setZdy3(String zdy3) {
		this.zdy3 = zdy3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.zdy4
	 * @return  the value of sys_dictype.zdy4
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getZdy4() {
		return zdy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.zdy4
	 * @param zdy4  the value for sys_dictype.zdy4
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setZdy4(String zdy4) {
		this.zdy4 = zdy4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dictype.zdy5
	 * @return  the value of sys_dictype.zdy5
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public String getZdy5() {
		return zdy5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dictype.zdy5
	 * @param zdy5  the value for sys_dictype.zdy5
	 * @mbggenerated  Sun Jun 28 10:58:04 CST 2015
	 */
	public void setZdy5(String zdy5) {
		this.zdy5 = zdy5;
	}
}